### PR TITLE
docs Updated members.json file

### PR DESCRIPTION
**Pull request by satyacasm**
Fixes issue #33 

**Before**
image

**After**
image

### CODE REVIEW

**Comment by AkhileshManda** [comment]
@DhruvDave12 changes LGTM, if you want to suggest any changes do tell.

**Review by DhruvDave12 — COMMENTED** [review]
Amitvikram Dwivedi sir, Shivansh Kumar sir are not in the list. Add them and again check if all the members are present in it.

**Comment by satyacasm** [comment]
Added few more members

**Comment by DhruvDave12** [comment]
LGTM, merging. Good work @satyacasm 👍

**Pull request merged**
