### PR TITLE
Add Events and Event Details page

### PR DESCRIPTION
**Pull request by Im-Madhur-Gupta**
## Work done
- Created Events page and Event Details page as per given Figma designs.
- Work consisted of making the events carousel, past events section, event details section including the countdown timer for an event.
- As per the assigned issue, the pages were made responsive.
- Also, I added the necessary structure of data using json files at required places.
- Contribution consisted of writing code using Next.js framework and vanilla CSS for styling.

## Dependencies added
- swiper

## Screenshots of contribution
Screenshot 2023-04-03 at 12 04 46 PM

Screenshot 2023-04-03 at 12 05 11 PM

Screenshot 2023-04-03 at 12 06 10 PM

Screenshot 2023-04-03 at 12 06 36 PM

### CODE REVIEW

**Review by ShivanshKumar — CHANGES_REQUESTED** [review]
You don't need three states to handle this problem, use only one state, year state, to handle button color, use ternary to check the value of "year" and set the colors accordingly.

**Comment by Im-Madhur-Gupta** [comment]
@ShivanshKumar sir I have added the changes you requested. Also, work regarding font size in vw issue is almost done.

**Comment by ShivanshKumar** [comment]
1. After changing to vw, the site is not responsive on many screen sizes
2.  I meant add ternary in styles tag, the thing you are doing right now is re-rendering the whole button

Do the following: style={{background: year?color1:color2}}

**Comment by Im-Madhur-Gupta** [comment]
> 1. After changing to vw, the site is not responsive on many screen sizes
> 2. I meant add ternary in styles tag, the thing you are doing right now is re-rendering the whole button
> 
> Do the following: style={{background: year?color1:color2}}

Sir I have added ternary to both the buttons on Event Archive page.

**Review by ShivanshKumar — APPROVED** [review]

**Pull request merged**
