### PR TITLE
added contact form, issue #35 resolved

### PR DESCRIPTION
**Pull request by ShravaniAK**
Screenshot 2022-10-24 at 12 02 41 PM

### CODE REVIEW

**Comment by ShravaniAK** [comment]
@Im-Madhur-Gupta please review and merge the pr.

**Comment by Im-Madhur-Gupta** [comment]
@ShravaniAK link this PR with the corresponding issue.

**Comment by ShravaniAK** [comment]
closes #35

**Comment by DhruvDave12** [comment]
LGTM!!

**Pull request merged**
